### ISSUE TITLE
[SUBMISSION] "Art as Code"

### ISSUE THREAD

**Issue by birthmarkbart** [cncf/cloudnativetv#31]
# Art as Code
## Description
Art as Code is a concept that humanizes the CNCF by giving people an opportunity to show the interplay between art (fine arts, music, literature, film, dance, video games, etc.) and what they do for work. By providing a space in which folks are free to showcase their passions, the idea is to continue the CNCF’s effort to be a welcoming and inclusive space where both code and non-code contributions are welcome.
Given the vast diversity of humans participating in the CNCF, there is an endless amount of talent and inspiration that can be tapped into and shared. It would provide a platform for KubeCons and other events to have a space for art to be shared.
Art as Code will feature interviews conducted by Bart Farrell and Nellie Tobey in which they will connect with different people from the CNCF ecosystem who have some kind of artistic background or interest they would like to share.
The show will be broadcast bi-weekly, with the possibility of having special episodes should there be the need/reason to do so.
After each show, Nellie would create a drawing to represent what the speaker had talked about. 
## Elevator Pitch
Our audience is anyone who wants to get know the incredible people in the CNCF in a more personal way. It’s a space for people who want to get inspired, who want a break from the purely technical although the show will give them the chance to see the fluidity between the technical and non-technical side.
In terms of engagement, apart from interviews we could easily have lightning rounds in a show n’ tell format, a talent show, and always make an effort to have young people and folks from underrepresented groups present in our content.
It would be a way to encourage SIGs to incorporate art, make their own playlists, create their own creative content/swag.
## Show Type
Interviews/Panel discussion
### Bart Farrell
Bart Farrell is a CNCF ambassador and leader of the Data on Kubernetes Community. Bart has done theater since he was 5, a musician since the age of 8, and currently works on audiovisual production in the CNCF through contributor experience videos. His mom is an artist, and he’s always had a keen interest in creativity. Bart brings his creativity to the DoK Community through rap music and the incorporation of artists as well as musicians from around the world.
### Nellie Tobey
Nellie Tobey is the Visual Learning Coordinator for the Data on Kubernetes Community. Nellie has been making art since she was very young, and has always enjoyed experimenting with all forms of art. Her role in the DoK Community is to bring technical concepts to life through drawings. She created the DoK’s first coloring book in their co-located event in Kubecon EU 2021, and has played an instrumental role in making complex ideas such as running stateful workloads on Kubernetes more tangible through her artwork.
### Prior experience
In the case of Bart- Leading the Data on Kubernetes Community, participating as a CNCF ambassador, engaging with the CNCF Students Group.
In the case of Nellie- Sharing her learning experiences through blogs and social media, Nellie shares her art and code willingly for any and all who wish to learn from it. Being the Visual Learning Coordinator of the Data on Kubernetes Community, Nellie is constantly creating artwork to engage the audience. 

![logo png](https://user-images.githubusercontent.com/74789611/123146899-b72b1380-d45e-11eb-9d95-2e0e97b18bdc.png)

**Comment by rawkode** [comment]
Fantastic submission 👍

**Comment by danpopSD** [comment]
100% out of the box , original, and wonderful submission. 👍

**Comment by rawkode** [comment]
Approved. Fantastic submission
