### ISSUE TITLE
[SUBMISSION] Cloud Next

### ISSUE THREAD

**Issue by dmueller2001** [cncf/cloudnativetv#32]
# Cloud.Next

## Description

In this series, we'll be giving the podium to project leads in emerging Cloud Native technology projects from across the CNCF ecosystem and adjacent communities. Each episode, we will bring together a panel of  special guest co-hosts to advise and coach project maintainers and other community members on the .Next steps to take to grow their communities, add new contributors and navigate the complexities of the vast and ever expanding Cloud Native ecosystem. 

Think of this as Dragon's Den for Cloud Native OSS initiatives but the friendlier more supportive version. 

New projects will get to 'pitch' their projects, and a panel of battle-harden CNCF and other OSS project leads and community developers along with live audience members 'advise' on how to ensure their projects' success

“Emerging technologies” are those initiatives that are still taking shape in the CNCF's sandboxes and incubators , Working Groups or TAGs or Kubenetes SIGs or collaborations/integrations with adjacent communities. Emerging technologies can be pre-product, purely upstream work...or even speculative intiatives and road map updates. 

"Community development" in open source ecosystems is increasingly complex. For new project leads, cross-community collaboration can be daunting. Aligning priorities and road maps with adjacent OSS projects and communities sometimes seems more like an art form but in reality requires a more methodical and data-driven approach. We'll do some deep dives to examine some of the interdependencies and interrelationships using some of the tools and techniques to gain insights an for growth and collaboration. 

For Emerging Tech project leads, it's a chance to get feedback on their project, float new ideas, reach new audiences, recruit new contributors and learn from some mistakes and successes of CNCF Open Source community leads. 

For CNCF audiences, it's a opportunity to get a quick intro and demo of these emerging new technologies, hear a bit about the project's plans for the future AND find out how to get involved. 

## Elevator Pitch to Emerging Tech Leads

Here's your chance to showcase your emerging projects, tech initiatives and get direct feedback from the audience along with mentoring from open source community leads on how to navigate the CNCF ecosystem. 

## Audience 

Technical 

## Show Type
Briefings by project leads with deep dive demos and road maps with live Q/A from the audience. Submissions via google form 

## Creative/Look/Logo requirements

- Logo : Koi fish in a recycling/interconnect loop (Kubernetes+Insights+Observability)
- Colors : CNCF branded colors
- Motifs : KOI, Recycle 

### Host Name
Diane Mueller and guest hosts
(if you are interested in co-hosting, drop a comment in the issue or ping me on twitter at "pythondj" )

### Prior experience

Host of OpenShift Commons and openshift.tv 
CNCF ambassador
Director, Community Development at Red Hat
Author, From Art to Science: The Evolution of Community Development
https://ieeexplore.ieee.org/document/8805055

**Comment by rawkode** [comment]
Hi Diane,

Thank you for your submission.

The co-chairs have reviewed and we are unable to accept the submission in its current form. We believe that the current proposal is very similar to existing shows, namely 100Days of Cloud Native and Cloud Native Classroom.

> As an added bonus, we'll be offering mentoring tips for growing your communities, enrolling new contributors and generally help you connect the dots to help facilitate alignment with existing CNCF projects and adjacent communities.

We did find the mentorship angle rather interesting and would welcome a submission that focused more on this and explained how this would work in a live stream setting.

Thanks again,
We look forward to any future submissions.

**Comment by danpopSD** [comment]
I think we should leave the Submission Open.  this is to allow Diane and the team to discuss any refinement based on these suggestions. i like the concept of Sandbox projects having a place to show what they do.

**Comment by dmueller2001** [comment]
We'll tweek the submission to focus more on mentoring on community development aspects for new project leads. Thanks for the feedback!

**Comment by danpopSD** [comment]
+1 strong approve.  love the revamp @dmueller2001

**Comment by danpopSD** [comment]
Welcome to Cloud Native.tv !

**Comment by dmueller2001** [comment]
yahoo! looking forward to working with y'all!
