### ISSUE TITLE
"[SHOW ONBOARDING] .edYOU"

### ISSUE THREAD

**Issue by xmulligan** [cncf/cloudnativetv#48]
Welcome to CloudNative.tv show Onboarding!
This is an issue created to help onboard your show into CloudNative.tv after the chairs have voted to accept your show. 
We would like to complete onboarding within two weeks of acceptance. 

From the project side, provide the following information:
- [x] What is your Twitch username so you can be added as a moderator to the channel?
- [x] Are you planning on using Restream or OBS?
     - [x] Restream: Please provide an email to share the login info through LastPass
     - [x] OBS: Please provide your Twitch email so you can have access to stream keys
- [x] Add your show description to the [shows folder](https://github.com/cncf/cloudnativetv/tree/main/shows)
- [x] Add your headshot to the [headshot folder](https://github.com/cncf/cloudnativetv/tree/main/headshots)
- [x] Add yourself to the SIG members in the README

Things that the CNCF will do or help the project to do: 
- [x] Get added to the Github repo
- [x] Create your logo
- [x] Upload it to the [branding repo](https://github.com/cncf/cloudnativetv/tree/main/branding)
- [x] Get stickers in the CNCF store

**Comment by xmulligan** [comment]
@kunal-kushwaha I realized you already started streaming, but we haven't fully onboarded you yet. Can you help me complete the above items?

**Comment by kunal-kushwaha** [comment]
Twitch username: `devkunal`

**Comment by xmulligan** [comment]
I've added you as a mod and your logos to the repo. Let me get the stickers if you can add the show description.

**Comment by kunal-kushwaha** [comment]
@xmulligan made a PR: https://github.com/cncf/cloudnativetv/pull/51

**Comment by kunal-kushwaha** [comment]
@xmulligan done!

**Comment by xmulligan** [comment]
Perfect, thanks! Working on getting your stickers up

**Comment by xmulligan** [comment]
https://store.cncf.io/products/cloudnative-tv-edyoudecal
