### ISSUE TITLE
[SUBMISSION] Cloud Native Cooking

### ISSUE THREAD

**Issue by celanthe** [cncf/cloudnativetv#50]
# Cloud Native Cooking

## Description

Some of the best conversations happen around the kitchen table. Have you ever wanted to get together with friends while not on the road? Share a meal and talk about the many intersections between cooking, community, and technology? We have. Kubernetes Contributor Celebration 2020 bake off winner Rin Oliver will be 'rintertaining' from their kitchen, cooking recipes submitted by the cloud native community alongside their many colleagues and friends in the industry. 

Whether it's a deep dive into how open source brings people together while baking muffins for brunch, or cooking a festive dinner while talking all things DevOps, this show brings together the many diverse cultures, experiences, and cuisines from around the world. Not only will we discuss technology, we'll chat about the many ways that food can bring people together to share, collaborate, and inspire one another.

### Show stream cadence

Biweekly

## Elevator Pitch

The audience for this show is not only tech industry professionals with an interest in baking and cooking, but new contributors to OSS who may feel intimidated about contributing to larger projects. They may have a recipe to share that they can submit to the show's community recipe repository that we will then cook on-air, and their merged PR into the interactive recipe book could be their first foray into OSS contribution.

## Show Type

An interview/Live cooking show

## Creative/Look/Logo requirements

- Logo : A plate of spaghetti/other food sitting on a cloud
- Colors : Red, White and a pale blue
- Motifs : Clouds, food

### Rin Oliver

Rin is a Technical Community Builder at Camunda. They enjoy discussing all things open source, with a particular focus on diversity in tech, improving hiring pipelines in OSS for those that are neurodivergent, and improving the developer experience for new and returning OSS contributors.

Rin is a Member of Kubernetes, a 2021 Board Member for The Diana Initiative in addition to speaking at TDI's 2020 event, and is currently working on the [Camunda Community Hub](https://github.com/camunda-community-hub/community) open source initiative in addition to their many other exciting projects at [Camunda](https://camunda.com/developers/).

### Prior experience

Rin is an internationally known speaker, having presented live at Mozilla Festival 2019 and virtually in 2021, Deserted Island DevOps 2021, Data on Kubernetes, DevOps Days Texas 2021, Write the Docs Portland 2021, DevRelCon Tokyo 2021, KubeCon EU 2020, and Kubernetes Contributor Summit 2019. They have also successfully produced podcasts and livestreams in a previous role for a number of years with The New Stack.

**Comment by danpop-chainguard** [comment]
@celanthe ,  with kubecon and the preplanning we are going to table the show submission evaluation process until November.  thank you for your patience

**Comment by celanthe** [comment]
> @celanthe , with kubecon and the preplanning we are going to table the show submission evaluation process until November. thank you for your patience

No worries, @danpopnyc! I look forward to hearing from you! :)
